version: '3'
services: 
  app: 
    container_name: tdd-laravel-rest-app
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: always
    ports:
     - 8000:80

  db:
    image: mysql
    container_name: tdd-laravel-rest-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: tdd-laravel-rest-db-admin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=tdd-laravel-rest-db
      - PMA_PORT=3306